; dataserver sources start with "<?"
short_open_tag = On
memory_limit = 1G
max_execution_time = 300
post_max_size = 32M
display_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED
date.timezone = UTC
